<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "netz_mtm"
 *
 * Auto generated by Extension Builder 2020-04-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'MTM',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Shouvik',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => 'uploads/netz_mtm/youtube/',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
